import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "modern-normalize/modern-normalize.css";
import "./globals.css";
import styles from "./layout.module.css";
import Header from "@/components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <div className={styles.container}>
          <Header></Header>
          {children}
        </div>
      </body>
    </html>
  );
}
